name: sap_work
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  internet_connection_checker: ^0.0.1+1
  infinite_scroll_pagination: ^3.1.0
  flutter_multi_formatter: ^2.1.3
  freezed_annotation: ^0.14.2
  progress_indicators: ^1.0.0
  shared_preferences: ^2.0.5
  connectivity_plus: ^1.0.3
  pull_to_refresh: ^2.0.0
  extended_image: ^4.1.0
  video_player: ^2.1.10
  file_picker: ^3.0.2+2
  path_provider: ^2.0.2
  flutter_bloc: ^7.0.0
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.9
  either_dart: ^0.1.2
  equatable: ^2.0.0
  provider: ^5.0.0
  shimmer: ^2.0.0
  get_it: ^7.1.3
  share: ^2.0.4
  formz: ^0.4.0
  intl: ^0.17.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  freezed: ^0.14.2

flutter_icons:
  image_path: "assets/app_icon/sapwork.png"
  android: true
  ios: tru

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg_icons/

  fonts:
    - family: NexaLight
      fonts:
        - asset: assets/fonts/Nexa-Light.ttf
    - family: NexaBold
      fonts:
        - asset: assets/fonts/Nexa-Bold.ttf
