//Tokens
const USER_TOKEN = 'USER_TOKEN';
const COMPANY_TOKEN = 'COMPANY_TOKEN';
const ADMIN_TOKEN = 'ADMIN_TOKEN';

//local files
const LOCAL_VACANCY_COMPANY = 'LOCAL_VACANCY_COMPANY';
const LOCAL_RESUME_USER = 'LOCAL_RESUME_USER';
const LOCAL_VACANCIES_COMPANY = 'LOCAL_VACANCIES_COMPANY';
const LOCAL_RESUMES_USER = 'LOCAL_RESUMES_USER';

//cached files
const CACHED_PROFILE_COMPANY = 'CACHED_PROFILE_COMPANY';
const CACHED_PROFILE_USER = 'CACHED_PROFILE_USER';
const CACHED_VACANCIES_COMPANY = 'CACHED_VACANCIES_COMPANY';
const CACHED_VACANCIES_USER = 'CACHED_VACANCIES_USER';
const CACHED_RESUMES_COMPANY = 'CACHED_RESUMES_COMPANY';
const CACHED_FAVORITES_VACANCIES_USER = 'CACHED_FAVORITES_VACANCIES_USER';
const CACHED_INVITES_VACANCIES_USER = 'CACHED_INVITES_VACANCIES_USER';
const CACHED_RESUMES_USER = 'CACHED_RESUMES_USER';
const CACHED_CATEGORIES = 'CACHED_CATEGORIES';
const CACHED_SPHERES = 'CACHED_SPHERES';
const CACHED_VACANCY_COMPANY = 'CACHED_VACANCY_COMPANY';
const CACHED_VACANCY_USER = 'CACHED_VACANCY_USER';
const CACHED_RESUME_USER = 'CACHED_RESUME_USER';
const CACHED_FEEDBACKS_VACANCY = "CACHED_FEEDBACKS_VACANCY";
const CACHED_FEEDBACKS_VACANCY_NO_SUBSCRIBE = "CACHED_FEEDBACKS_VACANCY_NO_SUBSCRIBE";
const CACHED_FEEDBACKS_RESUME = "CACHED_FEEDBACKS_RESUME";
const CACHED_STATUS_COMPANY = 'CACHED_STATUS_COMPANY';
const CACHED_CHATS_COMPANY = 'CACHED_CHATS_COMPANY';
const CACHED_CHATS_USER = 'CACHED_CHATS_USER';
const CACHED_ALL_CHATS_USER = 'CACHED_ALL_CHATS_USER';

//type
const USER = 'USER';
const COMPANY = 'COMPANY';
const POST_FAVORITES = 'POST_FAVORITES';
const DELETE_FAVORITES = 'POST_FAVORITES';

//for display
const EMPTY_STRING = "";
const EMPTY_TITLE_VACANCY = 'Введите название вакансии';
const EMPTY_TITLE_RESUME = 'Нажмите чтобы добавить резюме';
const EMPTY_TITLE_RESUME_VACANCY = 'Добавте резюме чтоби откликнут';
const DEFAULT_PHOTO = 'https://pmdoc.ru/wp-content/uploads/default-avatar.png';
//for arguments
const PROFILE_COMPANY_BLOC = 'PROFILE_COMPANY_BLOC';
const CORE_FEEDBACKS_BLOC = 'CORE_FEEDBACKS_BLOC';
const FEEDBACKS_VACANCY_BLOC = 'FEEDBACKS_VACANCY_BLOC';
const FEEDBACKS_COMPANY_BTN_CUBIT = 'FEEDBACKS_COMPANY_BTN_CUBIT';
const FEEDBACKS_USER_BTN_CUBIT = 'FEEDBACKS_USER_BTN_CUBIT';
const FEEDBACKS_RESUME_BLOC = 'FEEDBACKS_RESUME_BLOC';
const RESUMES_USER_BLOC = 'RESUMES_USER_BLOC';
const RESUME_USER_BLOC = 'RESUME_USER_BLOC';
const VACANCY_COMPANY_BLOC = 'VACANCY_COMPANY_BLOC';
const VACANCIES_COMPANY_BLOC = 'VACANCIES_COMPANY_BLOC';
const CORE_PROFILE_USER_BLOC = 'CORE_PROFILE_USER_BLOC';
const CORE_PROFILE_COMPANY_BLOC = 'CORE_PROFILE_COMPANY_BLOC';
const VACANCY_ID = 'VACANCY_ID';
const VACANCIES_USER_BLOC = 'VACANCIES_USER_BLOC';
const RESUMES_COMPANY_BLOC = 'RESUMES_COMPANY_BLOC';
const VACANCIES_USER_BTN_CUBIT = 'VACANCIES_USER_BTN_CUBIT';
const RESUMES_COMPANY_BTN_CUBIT = 'RESUMES_COMPANY_BTN_CUBIT';
const VARIABLE_FILTER_CUBIT = 'VARIABLE_FILTER_CUBIT';
const PROFILE_USER_BLOC = 'PROFILE_USER_BLOC';
const USER_ROLE = 'USER_ROLE';
const PHONE = 'PHONE';
const COMPANY_ROLE = 'COMPANY_ROLE';
const ADMIN_ROLE = 'ADMIN_ROLE';
const ROLE = 'ROLE';
const FROM = 'FROM';
const RESUME = 'RESUME';
const FEEDBACK = 'FEEDBACK';
const RESUME_SCREEN = 'RESUME_SCREEN';
const INVITE_SCREEN = 'INVITE_SCREEN';
const STATUS = 'STATUS';
const TYPE = 'TYPE';
const INVITE = 'INVITE';
const CHAT = 'CHAT';

//for blocs
const EMPTY_BLOC = "";

// vacancy company bloc
const VACANCY_COMPANY_BLOC_GET_VACANCY_FAILURE =
    'VACANCY_COMPANY_BLOC_GET_VACANCY_FAILURE';
const VACANCY_COMPANY_BLOC_ACTIVE_OR_DEACTIVATE_PROGRESS =
    'VACANCY_COMPANY_BLOC_ACTIVE_OR_DEACTIVATE_PROGRESS';
const VACANCY_COMPANY_BLOC_ACTIVE_OR_DEACTIVATE_SUCCEED =
    'VACANCY_COMPANY_BLOC_ACTIVE_OR_DEACTIVATE_SUCCEED';
const VACANCY_COMPANY_BLOC_ACTIVE_OR_DEACTIVATE_FAILURE =
    'VACANCY_COMPANY_BLOC_ACTIVE_OR_DEACTIVATE_FAILURE';
const VACANCY_COMPANY_BLOC_POST_VACANCY_PROGRESS =
    'VACANCY_COMPANY_BLOC_POST_VACANCY_PROGRESS';
const VACANCY_COMPANY_BLOC_POST_VACANCY_SUCCEED =
    'VACANCY_COMPANY_BLOC_POST_VACANCY_SUCCEED';
const VACANCY_COMPANY_BLOC_POST_VACANCY_FAILURE =
    'VACANCY_COMPANY_BLOC_POST_VACANCY_FAILURE';
const VACANCY_COMPANY_BLOC_POST_VACANCY_REQUIRED =
    'VACANCY_COMPANY_BLOC_POST_VACANCY_REQUIRED';
const VACANCY_COMPANY_BLOC_CHANGE_VACANCY_SUCCEED =
    'VACANCY_COMPANY_BLOC_CHANGE_VACANCY_SUCCEED';
const VACANCY_COMPANY_BLOC_CHANGE_VACANCY_FAILURE =
    'VACANCY_COMPANY_BLOC_CHANGE_VACANCY_FAILURE';

// vacancies company bloc
const VACANCIES_COMPANY_BLOC_CHANGE_VACANCIES_NAME_FAILURE =
    'VACANCIES_COMPANY_BLOC_CHANGE_VACANCIES_NAME_FAILURE';
const VACANCIES_COMPANY_BLOC_CHANGE_VACANCIES_NAME_SUCCEED =
    'VACANCIES_COMPANY_BLOC_CHANGE_VACANCIES_NAME_SUCCEED';

// resumes user bloc
const RESUMES_USER_BLOC_DELETE_RESUMES_SUCCEED =
    'RESUMES_USER_BLOC_DELETE_RESUMES_SUCCEED';
const RESUMES_USER_BLOC_DELETE_RESUMES_FAILURE =
    'RESUMES_USER_BLOC_DELETE_RESUMES_FAILURE';
const RESUMES_USER_BLOC_CHANGE_RESUMES_NAME_FAILURE =
    'RESUMES_USER_BLOC_CHANGE_RESUMES_NAME_FAILURE';
const RESUMES_USER_BLOC_CHANGE_RESUMES_NAME_SUCCEED =
    'RESUMES_USER_BLOC_CHANGE_RESUMES_NAME_SUCCEED';

//resume user bloc
const RESUME_USER_BLOC_ACTIVE_OR_DEACTIVATE_PROGRESS =
    'RESUME_USER_BLOC_ACTIVE_OR_DEACTIVATE_PROGRESS';
const RESUME_USER_BLOC_ACTIVE_OR_DEACTIVATE_SUCCEED =
    'RESUME_USER_BLOC_ACTIVE_OR_DEACTIVATE_SUCCEED';
const RESUME_USER_BLOC_ACTIVE_OR_DEACTIVATE_FAILURE =
    'RESUME_USER_BLOC_ACTIVE_OR_DEACTIVATE_FAILURE';
const RESUME_USER_BLOC_ADD_FILE_SUCCEED = 'RESUME_USER_BLOC_ADD_FILE_SUCCEED';
const RESUME_USER_BLOC_ADD_FILE_FAILURE = 'RESUME_USER_BLOC_ADD_FILE_FAILURE';
const RESUME_USER_BLOC_GET_RESUME_FAILURE =
    'RESUME_USER_BLOC_GET_RESUME_FAILURE';
const RESUME_USER_BLOC_POST_RESUME_PROGRESS =
    'RESUME_USER_BLOC_POST_RESUME_PROGRESS';
const RESUME_USER_BLOC_POST_RESUME_SUCCEED =
    'RESUME_USER_BLOC_POST_RESUME_SUCCEED';
const RESUME_USER_BLOC_POST_RESUME_FAILURE =
    'RESUME_USER_BLOC_POST_RESUME_FAILURE';
const RESUME_USER_BLOC_POST_RESUME_IS_NOT_VALIDATE =
    'RESUME_USER_BLOC_POST_RESUME_IS_NOT_VALIDATE';
const RESUME_USER_BLOC_CHANGE_EXTRA_BLOCK_FAILURE =
    'RESUME_USER_BLOC_CHANGE_EXTRA_BLOCK_FAILURE';
const RESUME_USER_BLOC_CHANGE_EXTRA_BLOCK_SUCCEED =
    'RESUME_USER_BLOC_CHANGE_EXTRA_BLOCK_SUCCEED';
const RESUME_USER_BLOC_CHANGE_RESUME_FAILURE =
    'RESUME_USER_BLOC_CHANGE_RESUME_FAILURE';
const RESUME_USER_BLOC_CHANGE_RESUME_SUCCEED =
    'RESUME_USER_BLOC_CHANGE_RESUME_SUCCEED';
const RESUME_USER_BLOC_ADD_EXTRA_BLOCKS_FAILURE =
    'RESUME_USER_BLOC_ADD_EXTRA_BLOCKS_FAILURE';
const RESUME_USER_BLOC_ADD_EXTRA_BLOCKS_SUCCEED =
    'RESUME_USER_BLOC_ADD_EXTRA_BLOCKS_SUCCEED';
const RESUME_USER_BLOC_DELETE_EXTRA_BLOCK_FAILURE =
    'RESUME_USER_BLOC_DELETE_EXTRA_BLOCK_FAILURE';
const RESUME_USER_BLOC_DELETE_EXTRA_BLOCK_SUCCEED =
    'RESUME_USER_BLOC_DELETE_EXTRA_BLOCK_SUCCEED';
const STAGES = 'STAGES';
const GRADES = 'GRADES';

// vacancies user bloc
const VACANCIES_USER_BLOC_POST_OR_DELETE_FAILURE =
    'VACANCIES_USER_BLOC_POST_OR_DELETE_FAILURE';
const VACANCIES_USER_BLOC_POST_OR_DELETE_SUCCEED =
    'VACANCIES_USER_BLOC_POST_OR_DELETE_SUCCEED';
const VACANCIES_USER_BLOC_SEARCH_VACANCIES_FAILURE =
    'VACANCIES_USER_BLOC_SEARCH_VACANCIES_FAILURE';
const VACANCIES_USER_BLOC_SEARCH_VACANCIES_SUCCEED =
    'VACANCIES_USER_BLOC_SEARCH_VACANCIES_SUCCEED';
const VACANCIES_USER_BLOC_FILTER_VACANCIES_FAILURE =
    'VACANCIES_USER_BLOC_FILTER_VACANCIES_FAILURE';
const VACANCIES_USER_BLOC_FILTER_VACANCIES_SUCCEED =
    'VACANCIES_USER_BLOC_FILTER_VACANCIES_SUCCEED';
const VACANCIES_USER_BLOC_FILTER_VACANCIES_REQUIRED =
    'VACANCIES_USER_BLOC_FILTER_VACANCIES_REQUIRED';

//profile user bloc
const PROFILE_USER_BLOC_UPLOAD_AVATAR_PROGRESS =
    'PROFILE_USER_BLOC_UPLOAD_AVATAR_PROGRESS';
const PROFILE_USER_BLOC_UPLOAD_AVATAR_SUCCEED =
    'PROFILE_USER_BLOC_UPLOAD_AVATAR_SUCCEED';
const PROFILE_USER_BLOC_UPLOAD_AVATAR_FAILURE =
    'PROFILE_USER_BLOC_UPLOAD_AVATAR_FAILURE';
const PROFILE_USER_BLOC_ADD_CONTACT_SUCCEED =
    'PROFILE_USER_BLOC_ADD_CONTACT_SUCCEED';
const PROFILE_USER_BLOC_ADD_CONTACT_FAILURE =
    'PROFILE_USER_BLOC_ADD_CONTACT_FAILURE';
const PROFILE_USER_BLOC_DELETE_CONTACT_SUCCEED =
    'PROFILE_USER_BLOC_DELETE_CONTACT_SUCCEED';
const PROFILE_USER_BLOC_DELETE_CONTACT_FAILURE =
    'PROFILE_USER_BLOC_DELETE_CONTACT_FAILURE';

//profile company bloc
const PROFILE_COMPANY_BLOC_UPLOAD_AVATAR_PROGRESS =
    'PROFILE_COMPANY_BLOC_UPLOAD_AVATAR_PROGRESS';
const PROFILE_COMPANY_BLOC_UPLOAD_AVATAR_SUCCEED =
    'PROFILE_COMPANY_BLOC_UPLOAD_AVATAR_SUCCEED';
const PROFILE_COMPANY_BLOC_UPLOAD_AVATAR_FAILURE =
    'PROFILE_COMPANY_BLOC_UPLOAD_AVATAR_FAILURE';
const PROFILE_COMPANY_BLOC_ADD_CONTACT_SUCCEED =
    'PROFILE_COMPANY_BLOC_ADD_CONTACT_SUCCEED';
const PROFILE_COMPANY_BLOC_ADD_CONTACT_FAILURE =
    'PROFILE_COMPANY_BLOC_ADD_CONTACT_FAILURE';
const PROFILE_COMPANY_BLOC_DELETE_CONTACT_SUCCEED =
    'PROFILE_USER_BLOC_DELETE_CONTACT_SUCCEED';
const PROFILE_COMPANY_BLOC_DELETE_CONTACT_FAILURE =
    'PROFILE_USER_BLOC_DELETE_CONTACT_FAILURE';

// feedbacks vacancy bloc
const FEEDBACKS_VACANCY_BLOC_POST_INVITE_PROGRESS =
    'FEEDBACKS_VACANCY_BLOC_POST_INVITE_PROGRESS';
const FEEDBACKS_VACANCY_BLOC_POST_INVITE_SUCCEED =
    'FEEDBACKS_VACANCY_BLOC_POST_INVITE_SUCCEED';
const FEEDBACKS_VACANCY_BLOC_POST_INVITE_FAILURE =
    'FEEDBACKS_VACANCY_BLOC_POST_INVITE_FAILURE';
const FEEDBACKS_VACANCY_BLOC_POST_INVITE_REQUIRED =
    'FEEDBACKS_VACANCY_BLOC_POST_INVITE_REQUIRED';
const FEEDBACKS_VACANCY_BLOC_POST_INVITE_NO_STATUS =
    'FEEDBACKS_VACANCY_BLOC_POST_INVITE_NO_STATUS';

// resumes company bloc
const RESUMES_COMPANY_BLOC_SEARCH_RESUMES_SUCCEED =
    'RESUMES_COMPANY_BLOC_SEARCH_RESUMES_SUCCEED';
const RESUMES_COMPANY_BLOC_SEARCH_RESUMES_FAILURE =
    'RESUMES_COMPANY_BLOC_SEARCH_RESUMES_FAILURE';
const RESUMES_COMPANY_BLOC_FILTER_RESUMES_SUCCEED =
    'RESUMES_COMPANY_BLOC_FILTER_RESUMES_SUCCEED';
const RESUMES_COMPANY_BLOC_FILTER_RESUMES_FAILURE =
    'RESUMES_COMPANY_BLOC_FILTER_RESUMES_FAILURE';

// vacancy user bloc
const VACANCY_USER_BLOC_SELECT_RESUME = 'VACANCY_USER_BLOC_SELECT_RESUME';

// feedbacks resume bloc
const FEEDBACKS_RESUME_BLOC_SEND_FEEDBACKS_PROGRESS =
    'FEEDBACKS_RESUME_BLOC_SEND_FEEDBACKS_PROGRESS';
const FEEDBACKS_RESUME_BLOC_SEND_FEEDBACKS_SUCCEED =
    'FEEDBACKS_RESUME_BLOC_SEND_FEEDBACKS_SUCCEED';
const FEEDBACKS_RESUME_BLOC_ACCEPT_FEEDBACKS_SUCCEED =
    'FEEDBACKS_RESUME_BLOC_ACCEPT_FEEDBACKS_SUCCEED';
const FEEDBACKS_RESUME_BLOC_SEND_FEEDBACKS_FAILURE =
    'FEEDBACKS_RESUME_BLOC_SEND_FEEDBACKS_FAILURE';

// admin bloc
const ADMIN_BLOC_ADD_CATEGORIES_SUCCEED = 'ADMIN_BLOC_ADD_CATEGORIES_SUCCEED';
const ADMIN_BLOC_ADD_CATEGORIES_FAILURE = 'ADMIN_BLOC_ADD_CATEGORIES_FAILURE';
const ADMIN_BLOC_ADD_SPHERES_SUCCEED = 'ADMIN_BLOC_ADD_SPHERES_SUCCEED';
const ADMIN_BLOC_ADD_SPHERES_FAILURE = 'ADMIN_BLOC_ADD_SPHERES_FAILURE';
const ADMIN_BLOC_DELETE_SUCCEED = 'ADMIN_BLOC_DELETE_SUCCEED';
const ADMIN_BLOC_DELETE_FAILURE = 'ADMIN_BLOC_DELETE_FAILURE';
const ADMIN_BLOC_SET_PRICE_SUCCEED = 'ADMIN_BLOC_SET_PRICE_SUCCEED';
const ADMIN_BLOC_SET_PRICE_FAILURE = 'ADMIN_BLOC_SET_PRICE_FAILURE';

// admin
const bool IS_ADMIN = false;
