//Tokens
const USER_TOKEN = 'USER_TOKEN';
const COMPANY_TOKEN = 'COMPANY_TOKEN';

//local files
const LOCAL_VACANCY_COMPANY = 'LOCAL_VACANCY_COMPANY';
const LOCAL_RESUME_USER = 'LOCAL_RESUME_USER';
const LOCAL_VACANCIES_COMPANY = 'LOCAL_VACANCIES_COMPANY';
const LOCAL_RESUMES_USER = 'LOCAL_RESUMES_USER';

//cached files
const CACHED_PROFILE_COMPANY = 'CACHED_PROFILE_COMPANY';
const CACHED_PROFILE_USER = 'CACHED_PROFILE_USER';
const CACHED_CONTACTS_USER = 'CACHED_CONTACTS_USER';
const CACHED_VACANCIES_COMPANY = 'CACHED_VACANCIES_COMPANY';
const CACHED_RESUMES_USER = 'CACHED_RESUMES_USER';
const CACHED_CATEGORIES = 'CACHED_CATEGORIES';
const CACHED_VACANCY_COMPANY = 'CACHED_VACANCY_COMPANY';
const CACHED_RESUME_USER = 'CACHED_RESUME_USER';
const CACHED_FEEDBACKS_VACANCY = "CACHED_FEEDBACKS_VACANCY";
const CACHED_STATUS_COMPANY = 'CACHED_STATUS_COMPANY';
const CACHED_CHATS_COMPANY = 'CACHED_CHATS_COMPANY';

//for display
const EMPTY_STRING = "";
const EMPTY_TITLE_VACANCY = 'Введите название вакансии';
const EMPTY_TITLE_RESUME = 'Нажмите чтобы добавить резюме';
const DEFAULT_PHOTO = 'https://pmdoc.ru/wp-content/uploads/default-avatar.png';

//for arguments
const PROFILE_COMPANY_BLOC = 'PROFILE_COMPANY_BLOC';
const CORE_FEEDBACKS_BLOC = 'CORE_FEEDBACKS_BLOC';
const FEEDBACKS_VACANCY_BLOC = 'FEEDBACKS_VACANCY_BLOC';
const FEEDBACKS_BTN_CUBIT = 'FEEDBACKS_BTN_CUBIT';

//for blocs
const EMPTY_BLOC = "";

// resumes user bloc
const RESUMES_USER_BLOC_SUCCEED_DELETE_RESUMES =
    'RESUMES_USER_BLOC_SUCCEED_DELETE_RESUMES';
const RESUMES_USER_BLOC_FAILURE_DELETE_RESUMES =
    'RESUMES_USER_BLOC_FAILURE_DELETE_RESUMES';
const RESUMES_USER_BLOC_FAILURE_EDIT_RESUMES_NAME =
    'RESUMES_USER_BLOC_FAILURE_EDIT_RESUMES_NAME';

//resume user bloc
const RESUME_USER_BLOC_ACTIVE_OR_DEACTIVATE_PROGRESS =
    'RESUME_USER_BLOC_ACTIVE_OR_DEACTIVATE_PROGRESS';
const RESUME_USER_BLOC_ACTIVE_OR_DEACTIVATE_SUCCEED =
    'RESUME_USER_BLOC_ACTIVE_OR_DEACTIVATE_SUCCEED';
const RESUME_USER_BLOC_ACTIVE_OR_DEACTIVATE_FAILURE =
    'RESUME_USER_BLOC_ACTIVE_OR_DEACTIVATE_FAILURE';
const RESUME_USER_BLOC_POST_RESUME_PROGRESS =
    'RESUME_USER_BLOC_POST_RESUME_PROGRESS';
const RESUME_USER_BLOC_POST_RESUME_SUCCEED =
    'RESUME_USER_BLOC_POST_RESUME_SUCCEED';
const RESUME_USER_BLOC_POST_RESUME_FAILURE =
    'RESUME_USER_BLOC_POST_RESUME_FAILURE';
const RESUME_USER_BLOC_CHANGE_EXTRA_BLOCK_FAILURE =
    'RESUME_USER_BLOC_CHANGE_EXTRA_BLOCK_FAILURE';
const RESUME_USER_BLOC_CHANGE_RESUME_FAILURE =
    'RESUME_USER_BLOC_CHANGE_RESUME_FAILURE';
const RESUME_USER_BLOC_ADD_STAGES_FAILURE =
    'RESUME_USER_BLOC_ADD_STAGES_FAILURE';
const RESUME_USER_BLOC_DELETE_EXTRA_BLOCK_FAILURE =
    'RESUME_USER_BLOC_DELETE_EXTRA_BLOCK_FAILURE';
const STAGES = 'STAGES';
const GRADES = 'GRADES';
